---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-rhdh
  namespace: {{ .Values.rhdh.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  app-config.yaml: |
    permission:
      enabled: true
      rbac:
        policies-csv-file: /opt/app-root/etc/rbac-policy.csv
        policyFileReload: true
        admin:
          users:
            - name: user:default/rdhd-admin
            
    app:
      title: Portal de Desarrolladores - RHCL Demo
      baseUrl: https://rhdh.{{ .Values.clusterDomain }}

    backend:
      baseUrl: https://rhdh.{{ .Values.clusterDomain }}
      cors:
        origin: https://rhdh.{{ .Values.clusterDomain }}
      reading:
        allow:
          - host: 'github.com'
          - host: 'raw.githubusercontent.com'
          - host: 'apicurio-registry.apps.cluster-62rsw.dynamic2.redhatworkshops.io'

    signInPage: oidc
    auth:
      session:
        secret: ${BACKEND_SECRET}
      environment: production
      providers:
        oidc:
          production:
            prompt: login
            metadataUrl: https://sso.{{ .Values.clusterDomain }}/realms/{{ .Values.keycloak.realmName }}/.well-known/openid-configuration
            clientId: ${AUTHENTICATION_OIDC_CLIENT_ID}
            clientSecret: ${AUTHENTICATION_OIDC_CLIENT_SECRET}
            signIn:
              resolvers:
                - resolver: preferredUsernameMatchingUserEntityName
    
    catalog:
      locations:
        - type: url
          target: https://raw.githubusercontent.com/RHDH-PoC-MX/camel-service/refs/heads/main/catalog-info.yaml
          rules:
            - allow: [Component, API, Location, Template, Domain, User, Group, System, Resource, Plugin, Package]
      rules:
        - allow: [Component, API, APIProduct, Location, Template, Domain, User, Group, System, Resource, Plugin, Package]
      providers:
        keycloakOrg:
          default:
            baseUrl: https://sso.{{ .Values.clusterDomain }}/
            realm: {{ .Values.keycloak.realmName }}
            loginRealm: {{ .Values.keycloak.realmName }}
            clientId: ${AUTHENTICATION_OIDC_CLIENT_ID}
            clientSecret: ${AUTHENTICATION_OIDC_CLIENT_SECRET}
            schedule:
              frequency: { minutes: 2}
              timeout: { minutes: 1}
              initialDelay: { seconds: 15 }
            signIn:
              resolvers:
                - resolver: emailMatchingUserEntityProfileEmail

    kubernetes: null