apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.gateway.name }}-route
  namespace: {{ .Values.gateway.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  host: api.{{ .Values.clusterDomain }}
  to:
    kind: Service
    name: external-istio
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect