apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  name: cluster
  annotations:
    # Wave 6: Se ejecuta al final junto con el resto de componentes de la aplicación
    argocd.argoproj.io/sync-wave: "2"
    # GITOPS MERGE: Fuerza a Argo CD a hacer un 'merge' parcial (Server-Side Apply)
    # en lugar de un reemplazo total del objeto del sistema
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  plugins:
  - kuadrant-console-plugin